[package]
name = "jrnl-cli"
version = "0.1.0"
authors = ["c0d01a5 <christopher.dieringer@walmartlabs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
job_scheduler = "1.2.1"
